# Generated by Django 5.0.7 on 2024-07-17 03:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
